
pdf: 
	pandoc -s -S --template=elsarticle.latex --biblio CommentReply.bib --csl proceedings-of-the-royal-society-b.csl CommentReply.md -o CommentReply.tex
	pdflatex CommentReply.tex	
	pdflatex CommentReply.tex

bib: 

